Add pending notifications incident history messages
Icinga/icinga-notifications-web pull request #127
Opened 2023-09-25 13:28 UTC by yhabteab

2023-10-25 08:31 UTC, julianbrost commented
Note that even though I already merged https://github.com/Icinga/icinga-notifications/pull/99, I didn't really test this PR because the current state doesn't work (presumably due to the change channel references to IDs change) and I can't rebase without conflicts (don't look too bad, but I didn't bother resolving them).

2024-04-10 07:08 UTC, nilmerg requested changes
The state must be translatable. The value in the database is not a label.

2024-04-29 06:57 UTC, nilmerg requested changes

2024-04-29 06:57 UTC, nilmerg commented on library/Notifications/Model/IncidentHistory.php
> +    public static function translateNotificationState(string $state): string
Add documentation

2024-04-29 06:57 UTC, nilmerg commented on library/Notifications/Model/IncidentHistory.php
> +                return t('sent', 'contact.notifications.state');
*notifications.transmission.state* fits better IMHO

2024-05-06 08:41 UTC, nilmerg commented on library/Notifications/Model/IncidentHistory.php
> +    public static function translateNotificationState(string $state): string
A docblock is obligatory.

2024-05-08 09:04 UTC, nilmerg approved these changes

2024-05-08 09:04 UTC, nilmerg requested changes
wait, there are conflicts

2024-05-24 09:41 UTC, nilmerg approved these changes

2024-05-24 09:42 UTC, merged