ObjectTags: Remove superfluous table name prefix from the column definition
Icinga/icinga-notifications-web pull request #151
Opened 2023-12-19 21:02 UTC by sukhwinder33445

resolves #150

2024-01-10 09:45 UTC, raviks789 submitted a review, later dismissed

2024-01-12 12:25 UTC, nilmerg requested changes
In the suggestion list, the name still starts lowercase

2024-01-17 15:29 UTC, nilmerg requested changes

2024-01-17 15:29 UTC, nilmerg commented on library/Notifications/Web/Control/SearchBar/ObjectSuggestions.php
> +                /** @var string $tagName */
Please take the chance to document this already in the model. Saves us a few more inline docs in the future.

2024-01-19 11:02 UTC, nilmerg approved these changes

2024-01-19 11:02 UTC, merged