Make incident age field intuitive
Icinga/icinga-notifications-web pull request #169
Opened 2024-04-03 13:39 UTC by raviks789

2024-04-24 06:36 UTC, sukhwinder33445 requested changes
Cannot save the incident age to db.

2024-04-24 12:31 UTC, raviks789 commented
> Cannot save the incident age to db.

As discussed offline this is a known issue in this PR, that does not need to be fixed as the PR #170 makes it obsolete.

2024-04-26 10:56 UTC, sukhwinder33445 requested changes

2024-04-26 10:56 UTC, sukhwinder33445 commented on library/Notifications/Widget/ItemList/EscalationConditionListItem.php
> +    public $conditionUnit;
Make it `protected` please.

2024-04-26 10:56 UTC, sukhwinder33445 commented on application/forms/EventRuleConfigElements/EscalationCondition.php
> +                        ]
Only whole numbers are supported now, `1.5h` is invalid.
- Please add `0.5` as step. 
- Remove second.
- Minimum allowed minute should be `1m`, not `0.5m`.

2024-05-15 11:01 UTC, sukhwinder33445 reviewed
- It is still possible to set `0.5m`, yes we cannot save it, or when reloading it becomes `1`, but it is a bug. You can simply add a default attribute `value` to the `$valUnit` element to prevent this behaviour.
- There is extra margin.
<img width="446" alt="Screenshot 2024-05-15 at 12 57 05" src="https://github.com/Icinga/icinga-notifications-web/assets/54990055/2575c287-fef8-4a73-9b52-fa0a3c55e0b5">

2024-05-15 13:03 UTC, raviks789 commented on application/forms/EventRuleConfigForm.php
> +                    && count($matches) === 3
I think this can be implemented in a more simpler way using `str_split`. I will make the changes.

2024-05-16 07:31 UTC, sukhwinder33445 requested changes
Each automatic submit of the form resets the `incident_age` value.

2024-05-16 08:38 UTC, raviks789 commented
> Each autosubmit of the form resets the `incident_age` value.

This should be fixed now.

2024-05-16 10:45 UTC, sukhwinder33445 approved these changes
LGTM

2025-08-13 14:35 UTC, nilmerg commented
Obsoleted by #159

2025-08-13 14:35 UTC, closed without merging