ChannelForm: Render default values as element values
Icinga/icinga-notifications-web pull request #175
Opened 2024-04-11 09:51 UTC by raviks789

Instead of rendering default values as placeholders, render them as element values.

2024-04-12 09:02 UTC, nilmerg commented on application/forms/ChannelForm.php
> +
Please remove and avoid that null values are stored in the database instead.

2024-04-12 09:06 UTC, nilmerg commented on application/forms/ChannelForm.php
> +                $elemOptions
Please undo these redundant changes

2024-04-12 12:22 UTC, nilmerg requested changes

2024-04-12 12:22 UTC, nilmerg commented on application/forms/ChannelForm.php
> +        }
You can do both things with array_filter

2024-04-12 13:47 UTC, nilmerg requested changes

2024-04-12 13:47 UTC, nilmerg commented on application/forms/ChannelForm.php
> +         */
single line still, pls

2024-04-12 13:47 UTC, nilmerg commented on application/forms/ChannelForm.php
> +     * Get the element type config type of the object
*Get the element type for the given option type*

2024-04-12 13:47 UTC, nilmerg commented on application/forms/ChannelForm.php
> +     * @param string $configType The config type of the object
*The option type*

2024-04-12 14:14 UTC, raviks789 commented on application/forms/ChannelForm.php
> +     * @param string $configType The option type of the object
Supposed to be _The option type_. I have corrected it.

2024-04-12 14:38 UTC, nilmerg reviewed
Looks fine now. But I don't like the handling of defaults for required elements: https://github.com/Icinga/icinga-notifications/issues/172

2024-05-24 08:29 UTC, nilmerg requested changes
Default values, that are not adjusted by the user, **must not** be written to database.

2024-05-24 09:09 UTC, nilmerg approved these changes

2024-05-24 09:38 UTC, merged