Move source icon in incident detail to the header
Icinga/icinga-notifications-web pull request #181
Opened 2024-04-22 15:29 UTC by raviks789

fixes #161

2024-04-24 10:00 UTC, sukhwinder33445 requested changes
- The icon is no longer aligned in the center due to this change (https://github.com/Icinga/icinga-notifications-web/commit/bae69e5cbb08add2cf5978e76427356b0875aa5a)
- The icons in the list should be statically aligned.
<img width="661" alt="Screenshot 2024-04-24 at 11 48 58" src="https://github.com/Icinga/icinga-notifications-web/assets/54990055/fe299056-3278-4b00-af08-ec68707dcf9b">

2024-04-26 08:46 UTC, ncosta-ic commented
> * The icon is no longer aligned in the center due to this change ([bae69e5](https://github.com/Icinga/icinga-notifications-web/commit/bae69e5cbb08add2cf5978e76427356b0875aa5a))
> 
> * The icons in the list should be statically aligned.
>

I stumbled accross the same problem and fixed it by adding a `margin-top: .15em` to the `i.icon` rule for `.source-icon` in `public/css/common.less`
I will not include this change in my PR (https://github.com/Icinga/icinga-notifications-web/pull/166) but it should be an easy fix.

2024-04-26 08:56 UTC, sukhwinder33445 commented
> I stumbled accross the same problem and fixed it by adding a `margin-top: .15em` to the `i.icon` rule for `.source-icon` in `public/css/common.less`

It should also be fixed if you only remove this change. ([bae69e5](https://github.com/Icinga/icinga-notifications-web/commit/bae69e5cbb08add2cf5978e76427356b0875aa5a))

2024-04-26 12:31 UTC, ncosta-ic commented
> > I stumbled accross the same problem and fixed it by adding a `margin-top: .15em` to the `i.icon` rule for `.source-icon` in `public/css/common.less`
> 
> It should also be fixed if you only remove this change. ([bae69e5](https://github.com/Icinga/icinga-notifications-web/commit/bae69e5cbb08add2cf5978e76427356b0875aa5a))
![source_icon_alignment](https://github.com/Icinga/icinga-notifications-web/assets/146938323/ca0d9774-c7ea-4065-bba8-704847cccd3e)
(The red box should be aligned with to the cyan guides)

I quickly compared all three variants:
- vertical-align: top
- vertical-align: top, margin-top: .15em
- without both css rules

From my point of view, the second option is also not quite right, but it's much closer to be perfectly aligned than the other two variants.

2024-05-03 08:09 UTC, nilmerg requested changes
The placement of the icon should be fixed separately.

2024-05-03 08:09 UTC, nilmerg commented on public/css/list/incident-list.less
> +.incident-list .list-item {
This doesn't seem to be specific to the incident list. The event list could also need it, so please move this to common.less

2024-05-03 09:12 UTC, raviks789 commented on library/Notifications/Widget/ItemList/IncidentHistoryListItem.php
> -                (new SourceIcon(SourceIcon::SIZE_BIG))->addHtml($this->item->event->object->source->getIcon())
You were right, I have removed the join now.

2024-05-06 07:47 UTC, nilmerg requested changes
> The placement of the icon should be fixed separately.

With this, I meant the placement of the icon inside the circle. Essentially, my answer to the discussion above.

Now, you've dismissed your own change that added a small gap to the right. I didn't mean you to do this! I still think it's suitable and a visual improvement. *If applied to the incident **and** events list*.

2024-05-06 07:47 UTC, nilmerg commented on library/Notifications/Widget/ItemList/IncidentListItem.php
> +            ]);
With this, a translator has the option to move the time representation.

```suggestion
           $meta->addHtml(FormattedString::create(
               $this->translate('closed %s', '(incident) ... <relative time>'),
               new TimeAgo($this->item->recovered_at->getTimestamp())
           ));
```

2024-05-24 09:37 UTC, nilmerg approved these changes

2024-05-24 09:38 UTC, merged