Move schedule to primary list
Icinga/icinga-notifications-web pull request #186
Opened 2024-04-30 11:38 UTC by sukhwinder33445

resolves #162

2024-04-30 12:24 UTC, sukhwinder33445 commented
The `add/editEntryAction()` of `SchedulerController` uses `$this->sendExtraUpdates(['#col2'])` to update the entry in the calendar. But if there is only one column (list #col1 is closed), the hardcoded `#col2` in `sendExtraUpdates` cannot update the calendar.

2024-05-03 08:52 UTC, nilmerg requested changes

2024-05-03 08:52 UTC, nilmerg commented on library/Notifications/Widget/ItemList/ScheduleListItem.php
> + * Channel item of a channel list. Represents one database row.
Ehh?

2024-05-03 08:52 UTC, nilmerg commented on library/Notifications/Model/Schedule.php
> -        ];
undo this unnecessary change

2024-05-03 08:52 UTC, nilmerg commented on application/controllers/ScheduleController.php
> +        }
This is/was only for testing purposes which shouldn't have been introduced to `main` to begin with. Remove this please.

2024-05-03 08:52 UTC, nilmerg commented on application/controllers/SchedulesController.php
> -        $this->controls->addAttributes(['class' => 'schedule-controls']);
I miss this in the new controller.

2024-05-03 08:52 UTC, nilmerg commented on application/controllers/SchedulesController.php
> +    public function getFilter(): Filter\Rule
Make this private as well, as is the property

2024-05-03 13:14 UTC, nilmerg approved these changes
please rebase

2024-05-03 14:29 UTC, merged