Incremental config updates
Icinga/icinga-notifications-web pull request #187
Opened 2024-05-02 13:19 UTC by sukhwinder33445

requires https://github.com/Icinga/icinga-notifications/pull/191

2024-05-14 08:15 UTC, sukhwinder33445 commented
Note to myself:
No changes have been made to the following forms as they will change completely based on the existing PRs:

- SaveEventRuleForm
- EntryForm
- EscalationRecipientForm
- ScheduleForm

2024-06-20 12:15 UTC, oxzi commented on application/forms/ChannelForm.php
> +            $channel['changed_at'] = time();
Both the [schema](https://github.com/Icinga/icinga-notifications/blob/24b62333d98d62042be598dc3806e323599527b4/schema/pgsql/upgrades/031.sql#L1-L3) and the [Go code](https://github.com/Icinga/icinga-notifications/blob/24b62333d98d62042be598dc3806e323599527b4/internal/channel/channel.go#L23-L24) are using millisecond precision. Writing seconds in this column results in way smaller values by a factor of 1k, resulting in a non-update from the daemon. Please use millisecond precision for all tables throughout your code.

2024-07-02 08:00 UTC, nilmerg commented on library/Notifications/Model/RuleEscalationRecipient.php
> + * @property int $channel_id
these are all nullable

2024-07-02 08:01 UTC, nilmerg commented on library/Notifications/Model/RuleEscalationRecipient.php
> + * @property string $value
what's this??

2024-07-02 14:37 UTC, nilmerg requested changes
forms only

2024-07-02 14:37 UTC, nilmerg commented on application/forms/ChannelForm.php
> +                        ? $this->translate('Cannot delete channel, contacts or event rules are using it')
*Channel is still referenced as a contact's default channel or in an event rule's escalation*

2024-07-02 14:37 UTC, nilmerg commented on application/forms/RotationConfigForm.php
> -        }
This should be kept here. It's not used to populate the form's inputs directly and may be of disadvantage in `fetchDbValues` as if called twice, resets the properties.

2024-07-02 14:37 UTC, nilmerg commented on application/forms/RotationConfigForm.php
>                      $this->db->delete('timeperiod_entry', ['id = ?' => $timeperiodEntry->id]);
What now? Marked or not?

2024-07-02 14:37 UTC, nilmerg commented on application/forms/SaveEventRuleForm.php
> +            $db->update('rule', $data, ['id = ?' => $id]);
Doesn't this miss `changedAt`?

2024-07-03 15:16 UTC, nilmerg commented on application/forms/RotationConfigForm.php
> +            }
This shouldn't be required. Just update the code to access what `fetchDbValues()` returns, please.

2024-07-04 09:01 UTC, nilmerg commented on library/Notifications/Model/RuleEscalationRecipient.php
> + * @property string $value
These are still here!

2024-07-05 11:40 UTC, nilmerg requested changes

2024-07-05 11:40 UTC, nilmerg commented on application/controllers/SourcesController.php
> +                Notification::success(sprintf(t('Add new source %s successfully'), $form->getSourceName()));
~~Add~~**Added**

2024-07-08 07:47 UTC, nilmerg requested changes
Looks okay now. Though, please try to centralize the registration of `deleted=n` in queries.

Take a look at the `Database` trait and it's `ON_ASSEMBLE_SELECT` listener. There you should be able to check a select whether it queries one of the tables with this column and add the filter for it.

You might need to ignore selects which already filter explicitly for `deleted=y`.

2024-07-09 11:38 UTC, nilmerg requested changes

2024-07-09 11:38 UTC, nilmerg commented on application/forms/ContactGroupForm.php
> +                        'contact_id IN (?)'     => $toAdd
Didn't this filter for `deleted=y` previously?

2024-07-09 11:38 UTC, nilmerg commented on library/Notifications/Widget/Timeline/Rotation.php
> +                ),
Can be removed as discussed.

2024-07-09 13:47 UTC, nilmerg commented on library/Notifications/Model/Rotation.php
> +     * The call must be wrapped in a transaction
```php
$transationStarted = false;
if (! $db->inTransaction()) {
    $transactionStarted = true;
    $db->beginTransaction();
}

...

if ($transactionStarted) {
    $db->commitTransaction();
}
```

2024-07-09 13:50 UTC, nilmerg commented on library/Notifications/Model/Rotation.php
> +        }
```php
if ($this->timeperiod instanceof Timeperiod) {
    $timeperiod = $this->timeperiod;
} else {
    $timeperiod = $this->timeperiod->first();
}
```

2024-07-10 08:18 UTC, nilmerg requested changes

2024-07-10 08:18 UTC, nilmerg commented on library/Notifications/Model/Rotation.php
> +     * The call must be wrapped in a transaction
The comment is now obsolete.

2024-07-10 08:18 UTC, nilmerg commented on library/Notifications/Model/Rotation.php
> +            $timeperiodId = $this->timeperiod->columns('id')->first();
Above you fetch the id, here the entire row.

2024-07-10 12:30 UTC, nilmerg reviewed
:hourglass_flowing_sand:

2024-07-11 11:22 UTC, nilmerg requested changes

2024-07-11 11:22 UTC, nilmerg commented on application/forms/ChannelForm.php
> +                        Filter::equal('contact.default_channel_id', $this->channelId)
The second filter is already covered by the first query above.

2024-07-11 13:07 UTC, nilmerg approved these changes

2024-07-12 07:52 UTC, merged