Usergroup configuration
Icinga/icinga-notifications-web pull request #188
Opened 2024-05-22 07:15 UTC by sukhwinder33445

2024-05-22 07:37 UTC, sukhwinder33445 commented on application/controllers/ContactGroupController.php
> +    private $db;
As `Database::get()` returns a singleton instance, you can use the method directly.

2024-05-22 07:37 UTC, sukhwinder33445 commented on application/controllers/ContactGroupsController.php
> +    private $db;
Please remove as described above.

2024-05-22 07:37 UTC, sukhwinder33445 commented on application/controllers/ContactGroupsController.php
> +        if ($this->getRequest()->getActionName() === 'index') {
Unwrap please.

2024-05-22 07:37 UTC, sukhwinder33445 commented on library/Notifications/Widget/MemberSuggestions.php
> +    protected function assemble()
Add return type, please.

2024-05-22 07:37 UTC, sukhwinder33445 commented on library/Notifications/Widget/MemberSuggestions.php
> +    public function forRequest(ServerRequestInterface $request)
Add return type, please.

2024-05-22 07:45 UTC, sukhwinder33445 commented on application/controllers/ContactGroupsController.php
> +    protected function addAction(): void
Please make these methods `public`.

2024-05-22 07:46 UTC, sukhwinder33445 commented on application/controllers/ContactGroupsController.php
> +                    // close the modal and refresh col1
Please remove this comment. The function already makes it obvious.

2024-05-22 07:51 UTC, sukhwinder33445 commented on application/controllers/ContactGroupsController.php
> +        $this->setAutorefreshInterval(30);
Please remove it.

2024-05-22 08:42 UTC, sukhwinder33445 commented on application/forms/ContactGroupForm.php
> +
You can simplify it:
```suggestion
if (! isset($data['group']['group_name'], $data['group']['group_members'])) {
            return null;
}
```

2024-05-22 09:09 UTC, sukhwinder33445 commented on application/controllers/ContactGroupsController.php
> +                    Notification::error(t('New group could not be added'));
Use `Failed to create new contact group` instead, please.

2024-05-22 09:11 UTC, sukhwinder33445 commented on application/controllers/ContactGroupsController.php
> +                    $this->closeModalAndRefreshRemainingViews($this->getRequest()->getUrl()->getAbsoluteUrl());
Please move it outside the conditions.

2024-05-23 12:35 UTC, sukhwinder33445 commented on application/controllers/ContactGroupsController.php
> +    protected function addContent(ValidHtml $content): ContactGroupsController
Please use self as return type.

2024-05-27 10:07 UTC, raviks789 requested changes
IMO, you need to either disable the `Delete` button for contacts belonging to a contact group or show error notification why the contact cannot be deleted. Currently, you get the sql error, with error trace.

Edit: You could also check if the contact belongs to an escalation. Same goes for contact groups.

2024-05-27 10:07 UTC, raviks789 commented on library/Notifications/Widget/MemberSuggestions.php
> +    public function setSearchTerm(string $term): self
This method is not used outside the class. Is there a reason, why this method is public?

2024-05-27 10:07 UTC, raviks789 commented on library/Notifications/Widget/MemberSuggestions.php
> +    public function setOriginalValue(string $term): self
Same here.

2024-05-27 10:07 UTC, raviks789 commented on library/Notifications/Widget/MemberSuggestions.php
> +    public function excludeTerms(array $terms): self
Same here

2024-05-28 10:28 UTC, sukhwinder33445 commented on application/controllers/ContactGroupController.php
> +     */
Yes, the PHPDoc is not required.

2024-05-29 08:14 UTC, nilmerg requested changes

2024-05-29 08:14 UTC, nilmerg commented on application/forms/ContactGroupForm.php
> +        $this->storedValues = [
Don't store this temporarily, as discussed. Load the stored data in the same transaction as when applying changes.

2024-05-29 08:19 UTC, nilmerg commented on library/Notifications/Widget/ItemList/ContactListItem.php
> +        if (! empty($this->item->has_email)) {
@sukhwinder33445 told me. Though, the isset that was previously there would have made this way more clear. Now, either restore the isset or explain in a comment why this check is required.

2024-05-29 08:33 UTC, ncosta-ic commented on library/Notifications/Widget/ItemList/ContactListItem.php
> +        if (! empty($this->item->has_email)) {
@nilmerg I didn't touch that class as you can see through my commits: https://github.com/Icinga/icinga-notifications-web/pull/188/files/d490cd52975ded7891f3e7ec06503fc124616d8d

2024-05-29 08:43 UTC, nilmerg commented on library/Notifications/Widget/ItemList/ContactListItem.php
> +        if (! empty($this->item->has_email)) {
Oh. My bad. But it's @sukhwinder33445's turn anyway ;)

2024-05-31 06:58 UTC, sukhwinder33445 commented on application/forms/ContactGroupForm.php
> +        return $isUpdated;
This is only used to display the success message when something has been updated.

2024-05-31 07:41 UTC, sukhwinder33445 commented on application/controllers/ContactGroupsController.php
> +                    $this->switchToSingleColumnLayout();
Yes, the form can be kept open.

But there is another problem now, when the form stays open, it contains the controls and shows a small bar. I think that controls should not be displayed in the modal and requires a css fix.

2024-05-31 07:51 UTC, nilmerg commented on application/controllers/ContactGroupsController.php
> +                    $this->switchToSingleColumnLayout();
No, that's dependent on the `showCompact` and `disableLayout` params on the form's action

2024-05-31 07:54 UTC, nilmerg commented on application/forms/ContactGroupForm.php
> +            ->on(TermInput::ON_PASTE, $callValidation);
> php > var_dump(is_callable([new \DateTime(), 'getTimestamp']));
> bool(true)
> php >

2024-05-31 09:09 UTC, nilmerg commented on application/forms/ContactGroupForm.php
> +            ->on(TermInput::ON_PASTE, $callValidation);
Well. **That** is a reason. And probably why I wouldn't (and never did) use a method here.

2024-05-31 09:17 UTC, sukhwinder33445 commented on application/forms/ContactGroupForm.php
> +            ->on(TermInput::ON_PASTE, $callValidation);
So you think I should leave it as it is?

2024-05-31 11:46 UTC, ncosta-ic commented on application/forms/ContactGroupForm.php
> +            ->on(TermInput::ON_PASTE, $callValidation);
> Yes, but it doesn't work with protected methods. We can use `Closure::fromCallable([$this, 'validateTerms'])` which returns a closure, but I don't think it's much better than what we're already doing.

A closure seems wrong as you are supposed to pass it an object of a callable type (see [Events.php#L31-34](https://github.com/Icinga/ipl-stdlib/blob/main/src/Events.php#L31-L34))

As for the issue that apparently arises when using a protected method, the [php documentation](https://www.php.net/manual/en/language.types.callable.php#language.types.callable.passing) states the following:
> ... Accessing protected and private methods from within a class is allowed.

Did you test it? According to the PHP documentation a `array($this, 'methodName')` or the shorter form `[$this, 'methodname']` should work :thinking:

2024-05-31 12:02 UTC, sukhwinder33445 commented on application/forms/ContactGroupForm.php
> +            ->on(TermInput::ON_PASTE, $callValidation);
Yes, I have tested it. And it might work for the same class, but here we pass it to the `TermInput` instance.

2024-06-10 12:12 UTC, raviks789 submitted a review, later dismissed

2024-06-10 12:35 UTC, nilmerg requested changes
style checks are failing

2024-06-10 12:35 UTC, nilmerg commented on application/forms/ContactGroupForm.php
> +        return $groupIdentifier;
This cannot be null.

2024-06-10 12:35 UTC, nilmerg commented on library/Notifications/Common/Links.php
The `showCompact` and `_disableLayout` are only required when using the links as modal targets. As such they should only be added if required. This means that adding them here is wrong. So either don't add those methods here or remove the default parameters.

2024-06-10 12:35 UTC, nilmerg commented on application/controllers/ContactGroupsController.php
> +                }
This is impossible to occur. Remove the conditional block entirely, it's not needed as the form implementation catches errors by default.

2024-06-10 12:35 UTC, nilmerg commented on application/forms/ContactGroupForm.php
> +    private $termInput;
obsolete

2024-06-10 12:35 UTC, nilmerg commented on application/controllers/ContactGroupsController.php
> +        if ($this->getRequest()->getActionName() === 'index') {
Why is this necessary? All other actions don't show tabs, so I don't see a reason for this

2024-06-10 12:35 UTC, nilmerg commented on application/forms/ContactGroupForm.php
> +    }
Find the mistake:

![image](https://github.com/Icinga/icinga-notifications-web/assets/16668527/4dfb87e4-4cfd-4ca1-9790-a2d895683887)

2024-06-11 13:35 UTC, nilmerg requested changes
* [ ] Editing a previously empty group fails
* [ ] The control lines don't align: 
![image](https://github.com/Icinga/icinga-notifications-web/assets/16668527/5d61d4ed-49be-46d3-987c-e186f031ba5a)

2024-06-11 13:35 UTC, nilmerg commented on application/forms/ContactGroupForm.php
> +                ['name' => $values['group_name']],
> SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type bigint: "" CONTEXT: unnamed portal parameter $1 = ''

2024-06-11 14:55 UTC, nilmerg requested changes
Adding a group without members doesn't work

2024-06-11 15:09 UTC, nilmerg approved these changes

2024-06-11 15:16 UTC, merged