Provide `ObjectsRendererHook` for `icingadb
Icinga/icinga-notifications-web pull request #192
Opened 2024-05-28 09:56 UTC by sukhwinder33445

requires https://github.com/Icinga/ipl-web/pull/224

2024-05-28 13:44 UTC, raviks789 reviewed
Please rebase

2024-05-28 16:06 UTC, nilmerg requested changes

2024-05-28 16:06 UTC, nilmerg commented on library/Notifications/ProvidedHook/Notifications/ObjectsRenderer.php
> +                    Filter::equal('host.name',  $services['host'])
This results in false positives.

> a on b
> a on c
> b on c

Given that there's also a `b on b`, this will match it

2024-05-31 07:42 UTC, nilmerg requested changes

2024-05-31 07:42 UTC, nilmerg commented on library/Notifications/Widget/ItemList/EventListItem.php
> +use ipl\Html\HtmlString;
unused

2024-05-31 07:42 UTC, nilmerg commented on library/Notifications/Widget/ItemList/IncidentListItem.php
> +use ipl\Html\Text;
both unused

2024-05-31 14:02 UTC, nilmerg approved these changes

2024-05-31 14:02 UTC, merged