ContactForm: Fix saving and populating Rocketchat and Web hook type contact addresses
Icinga/icinga-notifications-web pull request #198
Opened 2024-06-04 11:27 UTC by raviks789

fix #197

2024-06-06 07:57 UTC, raviks789 commented on library/Notifications/Web/Form/ContactForm.php
>              foreach ($values->contact_address as $contactInfo) {
Yes, I did not notice it. Thank you for pointing it out.

2024-06-07 08:25 UTC, sukhwinder33445 requested changes

2024-06-07 08:28 UTC, raviks789 commented on library/Notifications/Web/Form/ContactForm.php
> +            $formValues = [
I don't think this to be incorrect as well, I just skipping the initializing the variable to empty array, as I already know what the array should be initially.

2024-06-07 08:30 UTC, raviks789 commented on application/controllers/ContactController.php
> +                $this->sendExtraUpdates(['#col1']);
I am doing this, because this is how the behavior is in event rules, schedules and I think in contact groups as well.

2024-06-07 08:40 UTC, sukhwinder33445 commented on library/Notifications/Web/Form/ContactForm.php
> +            $formValues = [
This is not wrong, just a bit cumbersome and can be simplified.

2024-06-07 08:42 UTC, sukhwinder33445 commented on application/controllers/ContactController.php
> +                $this->sendExtraUpdates(['#col1']);
Event rules and schedule have a detail view, contact opens the form directly.

2024-06-07 11:59 UTC, raviks789 commented on library/Notifications/Web/Form/ContactForm.php
> +            $formValues = [
I think this is a very subjective opinion. I would leave it the way it is.

2024-06-07 12:00 UTC, raviks789 commented on library/Notifications/Web/Form/ContactForm.php
> +                Contact::on($this->db)->withoutColumns(['id'])->assembleSelect()
Totally overlooked. Good that you noticed.

2024-06-12 08:27 UTC, sukhwinder33445 commented on library/Notifications/Web/Form/ContactForm.php
> +        return $contactUpdated;
Please do not declare the variable conditionally.

2024-06-12 09:22 UTC, sukhwinder33445 approved these changes

2024-06-12 09:22 UTC, merged